node {
  checkout scm
  def workspace = pwd()

  stage('Env check') {
	sh 'echo "Branch name:"'
	sh 'echo $BRANCH_NAME'
  }
  if (env.BRANCH_NAME == 'master') {
    stage ('Some Stage 1 for master') {
      sh 'echo "do something1"'
    }
    stage ('Another Stage for Master') {
      sh 'echo "do something else here"'
    }
  }

  else if (env.BRANCH_NAME == 'stage') {
    stage ('Some stage branch step') {
      sh 'echo "do something2"'
    }
    stage ('Deploy to stage target') {
      sh 'echo "do something else"'
    }
  }

  else {
    sh 'echo "Branch not applicable to Jenkins... do nothing"'
  }
}