node {
  checkout scm
  def workspace = pwd()

  if (env.BRANCH_NAME == 'master') {
    stage ('Some Stage 1 for master') {
      sh 'echo "do something for master"'
    }
    stage ('Another Stage for Master') {
      sh 'echo "do something else for master"'
    }
  }

  else if (env.BRANCH_NAME == 'stage') {
    stage ('Some stage branch step') {
      sh 'echo "do something for stage branch"'
    }
    stage ('Deploy to stage target') {
      sh 'echo "do something else deploy to stage target"'
    }
  }

  else {
    sh 'echo "Branch not applicable to Jenkins... do nothing"'
  }
}